import type { ContentEntry } from "./types.js"

export function generateContentListCode(options: {
  entries: ContentEntry[]
  buildDate: string
  generatedBy: string
}): string {
  const entriesCode = options.entries
    .map(
      (entry) => `  ${JSON.stringify(entry.slug)}: {
    id: ${JSON.stringify(entry.id)},
    slug: ${JSON.stringify(entry.slug)},
    path: ${JSON.stringify(entry.path)},
    contentPath: ${JSON.stringify(entry.contentPath)},
    image: ${JSON.stringify(entry.image)},
    imagePath: ${JSON.stringify(entry.imagePath)},
    title: ${JSON.stringify(entry.title)},
    description: ${JSON.stringify(entry.description)},
    publishedAt: ${JSON.stringify(entry.publishedAt)},
    updatedAt: ${JSON.stringify(entry.updatedAt)},
    author: ${JSON.stringify(entry.author)},
    imageAlt: ${JSON.stringify(entry.imageAlt)},
    body: ${JSON.stringify(entry.body)},
    html: ${JSON.stringify(entry.html)},
    isPublishedAtBuild: ${entry.isPublishedAtBuild},
  }`,
    )
    .join(",\n")

  return `// Auto-generated, manual changes will be lost.
// Generated by: ${options.generatedBy}
// Build date: ${options.buildDate}

import type { ContentEntry } from "@adaptive-ds/website-content-pipeline";

export type { ContentEntry } from "@adaptive-ds/website-content-pipeline";

export const buildDate = ${JSON.stringify(options.buildDate)} as const;

export const contentList = {
${entriesCode}
} as const satisfies Record<string, ContentEntry>;

export const allContent = Object.values(contentList);

export function contentBySlug(slug: string): ContentEntry | undefined {
  return contentList[slug as keyof typeof contentList];
}

export function isPublishedAtBuild(entry: ContentEntry): boolean {
  return entry.publishedAt < buildDate;
}

export function publishedContent(): ContentEntry[] {
  return allContent.filter((entry) => entry.publishedAt < buildDate);
}
`
}
