import type { ContentEntry } from "./types.js"

export function generateContentListCode(options: {
  entries: ContentEntry[]
  buildDate: string
  generatedBy: string
}): string {
  const entriesCode = options.entries
    .map(
      (entry) => `  ${JSON.stringify(entry.slug)}: {
    id: ${JSON.stringify(entry.id)},
    slug: ${JSON.stringify(entry.slug)},
    path: ${JSON.stringify(entry.path)},
    contentPath: ${JSON.stringify(entry.contentPath)},
    image: ${JSON.stringify(entry.image)},
    imagePath: ${JSON.stringify(entry.imagePath)},
    title: ${JSON.stringify(entry.title)},
    description: ${JSON.stringify(entry.description)},
    publishedAt: ${JSON.stringify(entry.publishedAt)},
    updatedAt: ${JSON.stringify(entry.updatedAt)},
    author: ${JSON.stringify(entry.author)},
    imageAlt: ${JSON.stringify(entry.imageAlt)},
  }`,
    )
    .join(",\n")

  return `// Auto-generated, manual changes will be lost.
// Generated by: ${options.generatedBy}
// Generated: ${options.buildDate}

import type { ContentEntry } from "@adaptive-ds/website-content-pipeline";

export type { ContentEntry } from "@adaptive-ds/website-content-pipeline";

export const contentList = {
${entriesCode}
} as const satisfies Record<string, ContentEntry>;

export const allContent = Object.values(contentList);

// The publish cutoff is the date this code runs. For a prerendered site that is
// the build date, so a scheduled post goes live on the next rebuild — no need to
// regenerate this file. A post is published once its date is today or earlier.
function today(): string {
  return new Date().toISOString().slice(0, 10);
}

export function contentBySlug(slug: string): ContentEntry | undefined {
  return contentList[slug as keyof typeof contentList];
}

export function isPublishedAtBuild(entry: ContentEntry, now: string = today()): boolean {
  return entry.publishedAt <= now;
}

export function publishedContent(now: string = today()): ContentEntry[] {
  return allContent.filter((entry) => entry.publishedAt <= now);
}
`
}
